knp_paginator:
    page_range: 5                       # Nombre de pages affichées dans la navigation
    default_options:
        page_name: page                 # Nom du paramètre de page dans l'URL
        sort_field_name: sort           # Nom du paramètre de tri dans l'URL
        sort_direction_name: direction  # Nom du paramètre de direction de tri dans l'URL
        distinct: true                  # Utiliser DISTINCT dans les requêtes SQL
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # Template de pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'                 # Template pour les liens de tri
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'                 # Template pour les filtres 