knp_snappy:
    pdf:
        enabled: true
        binary: '"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe"'
        options:
            encoding: 'UTF-8'
            enable-javascript: true
            javascript-delay: 1000
            no-stop-slow-scripts: true
            no-background: false
            lowquality: false
            enable-external-links: true
            enable-internal-links: true 