<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bus extends \App\Entity\Bus implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'date_arrive' => [parent::class, 'date_arrive', null, 16],
        "\0".parent::class."\0".'date_sortie' => [parent::class, 'date_sortie', null, 16],
        "\0".parent::class."\0".'imatriculation' => [parent::class, 'imatriculation', null, 16],
        "\0".parent::class."\0".'nb_place' => [parent::class, 'nb_place', null, 16],
        "\0".parent::class."\0".'station' => [parent::class, 'station', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'date_arrive' => [parent::class, 'date_arrive', null, 16],
        'date_sortie' => [parent::class, 'date_sortie', null, 16],
        'imatriculation' => [parent::class, 'imatriculation', null, 16],
        'nb_place' => [parent::class, 'nb_place', null, 16],
        'station' => [parent::class, 'station', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
