<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A1D1zOAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a1D1zOA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a1D1zOA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'busRepository' => ['privates', 'App\\Repository\\BusRepository', 'getBusRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'busRepository' => 'App\\Repository\\BusRepository',
            'entityManager' => '?',
            'logger' => '?',
            'mailer' => '?',
        ]);
    }
}
