<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MXVFYJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mX_vFYJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mX_vFYJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'busRepository' => ['privates', 'App\\Repository\\BusRepository', 'getBusRepositoryService', true],
        ], [
            'busRepository' => 'App\\Repository\\BusRepository',
        ]);
    }
}
