<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pm9OEOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pm9OE_o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pm9OE_o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bus' => ['privates', '.errored..service_locator.Pm9OE_o.App\\Entity\\Bus', NULL, 'Cannot autowire service ".service_locator.Pm9OE_o": it needs an instance of "App\\Entity\\Bus" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'bus' => 'App\\Entity\\Bus',
            'entityManager' => '?',
        ]);
    }
}
