<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RWGstl3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RWGstl3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RWGstl3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'station' => ['privates', '.errored..service_locator.RWGstl3.App\\Entity\\Station', NULL, 'Cannot autowire service ".service_locator.RWGstl3": it needs an instance of "App\\Entity\\Station" but this type has been excluded in "config/services.yaml".'],
        ], [
            'station' => 'App\\Entity\\Station',
        ]);
    }
}
