<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qb1UiqCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qb1UiqC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qb1UiqC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'partenaire' => ['privates', '.errored..service_locator.Qb1UiqC.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.Qb1UiqC": it needs an instance of "App\\Entity\\Partenaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'partenaire' => 'App\\Entity\\Partenaire',
        ]);
    }
}
