<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBus2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.E2gnoWj.App\Entity\Bus' shared service.
     *
     * @return \App\Entity\Bus
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.E2gnoWj": it needs an instance of "App\\Entity\\Bus" but this type has been excluded in "config/services.yaml".');
    }
}
