<?php

namespace ContainerLmfiG5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoitureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..gXe017.App\Entity\Voiture' shared service.
     *
     * @return \App\Entity\Voiture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..gXe017": it needs an instance of "App\\Entity\\Voiture" but this type has been excluded in "config/services.yaml".');
    }
}
