<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EgKIcAlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.egKIcAl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.egKIcAl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'voitureRepository' => ['privates', 'App\\Repository\\VoitureRepository', 'getVoitureRepositoryService', true],
        ], [
            'entityManager' => '?',
            'voitureRepository' => 'App\\Repository\\VoitureRepository',
        ]);
    }
}
