<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S4v6sfnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s4v6sfn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s4v6sfn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationsRepository' => ['privates', 'App\\Repository\\ReservationsRepository', 'getReservationsRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reservationsRepository' => 'App\\Repository\\ReservationsRepository',
        ]);
    }
}
