<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6fkHgaWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6fkHgaW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6fkHgaW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'voiture' => ['privates', '.errored..service_locator.6fkHgaW.App\\Entity\\Voiture', NULL, 'Cannot autowire service ".service_locator.6fkHgaW": it needs an instance of "App\\Entity\\Voiture" but this type has been excluded in "config/services.yaml".'],
        ], [
            'voiture' => 'App\\Entity\\Voiture',
        ]);
    }
}
