<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ci5Ix3ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ci5Ix3Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ci5Ix3Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bu' => ['privates', '.errored..service_locator.Ci5Ix3Z.App\\Entity\\Bus', NULL, 'Cannot autowire service ".service_locator.Ci5Ix3Z": it needs an instance of "App\\Entity\\Bus" but this type has been excluded in "config/services.yaml".'],
        ], [
            'bu' => 'App\\Entity\\Bus',
        ]);
    }
}
