<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ETZ7QbtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ETZ7Qbt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ETZ7Qbt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'partenaire' => ['privates', '.errored..service_locator.ETZ7Qbt.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.ETZ7Qbt": it needs an instance of "App\\Entity\\Partenaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'partenaire' => 'App\\Entity\\Partenaire',
        ]);
    }
}
