<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PhVsJulService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.phVsJul' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.phVsJul'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'station' => ['privates', '.errored..service_locator.phVsJul.App\\Entity\\Station', NULL, 'Cannot autowire service ".service_locator.phVsJul": it needs an instance of "App\\Entity\\Station" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'station' => 'App\\Entity\\Station',
        ]);
    }
}
