<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__GXe017Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..gXe017' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..gXe017'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'voiture' => ['privates', '.errored..service_locator..gXe017.App\\Entity\\Voiture', NULL, 'Cannot autowire service ".service_locator..gXe017": it needs an instance of "App\\Entity\\Voiture" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'slugger' => '?',
            'voiture' => 'App\\Entity\\Voiture',
        ]);
    }
}
