<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartenaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ETZ7Qbt.App\Entity\Partenaire' shared service.
     *
     * @return \App\Entity\Partenaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ETZ7Qbt": it needs an instance of "App\\Entity\\Partenaire" but this type has been excluded in "config/services.yaml".');
    }
}
