<?php

namespace ContainerCF3cG94;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoiture3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6fkHgaW.App\Entity\Voiture' shared service.
     *
     * @return \App\Entity\Voiture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6fkHgaW": it needs an instance of "App\\Entity\\Voiture" but this type has been excluded in "config/services.yaml".');
    }
}
