<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPC5Txp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPC5Txp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPC5Txp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPC5Txp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWPC5Txp\App_KernelDevDebugContainer([
    'container.build_hash' => 'WPC5Txp',
    'container.build_id' => '933f9d70',
    'container.build_time' => 1746114390,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPC5Txp');
